# Generated by Django 2.1 on 2019-07-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapflag',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
